export type DiagnosticCategory =
  | "Pemahaman Bilangan"
  | "Kelancaran Berhitung"
  | "Pecahan"
  | "Soal Cerita"
  | "Penalaran Logis";

export type DiagnosticQuestion = {
  id: string;
  gradeLevel: number;
  skillLevel: number;
  assessmentBand: "foundation" | "core" | "stretch";
  category: DiagnosticCategory;
  domain: string;
  skill: string;
  subskill: string;
  prerequisiteSkill: string;
  difficulty: "mudah" | "sedang" | "menantang";
  cognitiveType: "fluency" | "concept" | "application" | "reasoning";
  recommendationKey: string;
  misconceptionKey: string | null;
  diagnosticWeight: number;
  diagnosticVersion: string;
  prompt: string;
  options: string[];
  correctAnswer: string;
  explanation: string;
};

export type DiagnosticProfile = {
  level:
    | "Sangat Siap"
    | "Sesuai Jalur"
    | "Perlu Pendampingan"
    | "Fondasi Perlu Dikuatkan";
  tone: string;
  summary: string;
  recommendation: string[];
};

export type DiagnosticQuestionMeta = {
  skillLevel?: number;
  assessmentBand?: DiagnosticQuestion["assessmentBand"];
  domain?: string;
  skill?: string;
  subskill?: string;
  prerequisiteSkill?: string;
  cognitiveType?: DiagnosticQuestion["cognitiveType"];
  recommendationKey?: string;
  misconceptionKey?: string | null;
  diagnosticWeight?: number;
  diagnosticVersion?: string;
};

const gradeNames = Array.from(
  { length: 12 },
  (_, index) => `Kelas ${index + 1}`,
);

function defaultSkillFromCategory(category: DiagnosticCategory) {
  const map: Record<DiagnosticCategory, string> = {
    "Pemahaman Bilangan": "Number Sense",
    "Kelancaran Berhitung": "Calculation Fluency",
    Pecahan: "Fractions",
    "Soal Cerita": "Word Problem Modeling",
    "Penalaran Logis": "Logical Reasoning",
  };
  return map[category];
}

function defaultCognitiveType(
  category: DiagnosticCategory,
): DiagnosticQuestion["cognitiveType"] {
  if (category === "Kelancaran Berhitung") return "fluency";
  if (category === "Soal Cerita") return "application";
  if (category === "Penalaran Logis") return "reasoning";
  return "concept";
}

function defaultRecommendationKey(
  gradeLevel: number,
  category: DiagnosticCategory,
) {
  return `G${gradeLevel}_${defaultSkillFromCategory(category)
    .toUpperCase()
    .replace(/[^A-Z0-9]+/g, "_")}`;
}

function q(
  gradeLevel: number,
  id: string,
  category: DiagnosticCategory,
  difficulty: DiagnosticQuestion["difficulty"],
  prompt: string,
  options: string[],
  correctAnswer: string,
  explanation: string,
  meta: DiagnosticQuestionMeta = {},
): DiagnosticQuestion {
  const defaultSkill = defaultSkillFromCategory(category);
  const skill = meta.skill ?? defaultSkill;

  return {
    id: `g${gradeLevel}-${id}`,
    gradeLevel,
    skillLevel: meta.skillLevel ?? gradeLevel,
    assessmentBand: meta.assessmentBand ?? "core",
    category,
    domain: meta.domain ?? category,
    skill,
    subskill: meta.subskill ?? skill,
    prerequisiteSkill: meta.prerequisiteSkill ?? "",
    difficulty,
    cognitiveType: meta.cognitiveType ?? defaultCognitiveType(category),
    recommendationKey:
      meta.recommendationKey ?? defaultRecommendationKey(gradeLevel, category),
    misconceptionKey: meta.misconceptionKey ?? null,
    diagnosticWeight: meta.diagnosticWeight ?? 1,
    diagnosticVersion: meta.diagnosticVersion ?? "MATH_CHECKUP_V1",
    prompt,
    options,
    correctAnswer,
    explanation,
  };
}

const GRADE_1_DIAGNOSTIC_VERSION = "BSMATH_G1_V1";

const grade1DiagnosticV2: DiagnosticQuestion[] = [
  q(
    1,
    "v2-q01",
    "Pemahaman Bilangan",
    "mudah",
    "Hitung apel berikut: 🍎 🍎 🍎 🍎 🍎 🍎 🍎. Ada berapa apel?",
    ["6", "7", "8", "9"],
    "7",
    "Ada 7 apel. Hitung setiap apel satu kali.",
    {
      skillLevel: 1,
      assessmentBand: "foundation",
      domain: "Number Sense",
      skill: "Counting & Cardinality",
      subskill: "One-to-one Counting",
      cognitiveType: "concept",
      recommendationKey: "G1_COUNTING_CARDINALITY",
      misconceptionKey: "COUNT_OFF_BY_ONE",
      diagnosticWeight: 1,
      diagnosticVersion: GRADE_1_DIAGNOSTIC_VERSION,
    },
  ),
  q(
    1,
    "v2-q02",
    "Pemahaman Bilangan",
    "mudah",
    "Hitung bintang berikut: ⭐ ⭐ ⭐ ⭐ ⭐ ⭐ ⭐ ⭐ ⭐. Angka mana yang menunjukkan jumlah bintang?",
    ["8", "9", "10", "11"],
    "9",
    "Ada 9 bintang, jadi angka yang sesuai adalah 9.",
    {
      skillLevel: 1,
      assessmentBand: "foundation",
      domain: "Number Sense",
      skill: "Numeral-Quantity Connection",
      subskill: "Match Quantity to Numeral",
      prerequisiteSkill: "Counting & Cardinality",
      cognitiveType: "concept",
      recommendationKey: "G1_NUMBER_REPRESENTATION",
      diagnosticWeight: 1,
      diagnosticVersion: GRADE_1_DIAGNOSTIC_VERSION,
    },
  ),
  q(
    1,
    "v2-q03",
    "Pemahaman Bilangan",
    "mudah",
    "Kelompok A: ● ● ● ● ● ●  |  Kelompok B: ▲ ▲ ▲ ▲ ▲ ▲ ▲ ▲. Kelompok mana yang lebih banyak?",
    ["Kelompok A", "Kelompok B", "Sama banyak", "Tidak dapat ditentukan"],
    "Kelompok B",
    "Kelompok B memiliki 8 benda, sedangkan Kelompok A memiliki 6 benda.",
    {
      skillLevel: 1,
      assessmentBand: "foundation",
      domain: "Number Sense",
      skill: "Number Magnitude",
      subskill: "Compare Quantities",
      prerequisiteSkill: "Counting & Cardinality",
      cognitiveType: "reasoning",
      recommendationKey: "G1_NUMBER_MAGNITUDE",
      misconceptionKey: "MAGNITUDE_REVERSAL",
      diagnosticWeight: 1,
      diagnosticVersion: GRADE_1_DIAGNOSTIC_VERSION,
    },
  ),
  q(
    1,
    "v2-q04",
    "Pemahaman Bilangan",
    "sedang",
    "7 = 5 + __. Angka yang tepat adalah ...",
    ["1", "2", "3", "4"],
    "2",
    "5 ditambah 2 sama dengan 7.",
    {
      skillLevel: 1,
      assessmentBand: "foundation",
      domain: "Number Sense",
      skill: "Number Composition",
      subskill: "Part-Part-Whole within 10",
      prerequisiteSkill: "Counting & Cardinality",
      cognitiveType: "concept",
      recommendationKey: "G1_NUMBER_COMPOSITION",
      misconceptionKey: "PART_WHOLE_CONFUSION",
      diagnosticWeight: 1,
      diagnosticVersion: GRADE_1_DIAGNOSTIC_VERSION,
    },
  ),
  q(
    1,
    "v2-q05",
    "Kelancaran Berhitung",
    "mudah",
    "Ada 3 ikan, lalu datang 2 ikan lagi: 🐟 🐟 🐟 + 🐟 🐟. Berapa jumlah ikan sekarang?",
    ["4", "5", "6", "7"],
    "5",
    "3 ikan ditambah 2 ikan menjadi 5 ikan.",
    {
      skillLevel: 1,
      assessmentBand: "foundation",
      domain: "Operations",
      skill: "Addition",
      subskill: "Addition as Joining",
      prerequisiteSkill: "Number Composition",
      cognitiveType: "concept",
      recommendationKey: "G1_BASIC_ADDITION",
      diagnosticWeight: 1,
      diagnosticVersion: GRADE_1_DIAGNOSTIC_VERSION,
    },
  ),
  q(
    1,
    "v2-q06",
    "Penalaran Logis",
    "mudah",
    "Lanjutkan pola: 🔵 🔴 🔵 🔴 🔵 __",
    ["🔴", "🔵", "🟢", "🟡"],
    "🔴",
    "Pola bergantian biru, merah, biru, merah.",
    {
      skillLevel: 1,
      assessmentBand: "foundation",
      domain: "Algebraic Thinking",
      skill: "Pattern Recognition",
      subskill: "AB Pattern",
      cognitiveType: "reasoning",
      recommendationKey: "G1_PATTERN",
      diagnosticWeight: 1,
      diagnosticVersion: GRADE_1_DIAGNOSTIC_VERSION,
    },
  ),
  q(
    1,
    "v2-q07",
    "Pemahaman Bilangan",
    "mudah",
    "12, 13, 14, __. Bilangan berikutnya adalah ...",
    ["13", "14", "15", "16"],
    "15",
    "Urutan bertambah 1, jadi setelah 14 adalah 15.",
    {
      skillLevel: 1,
      assessmentBand: "core",
      domain: "Number Sense",
      skill: "Number Sequence",
      subskill: "Count Forward by One",
      prerequisiteSkill: "Counting & Cardinality",
      cognitiveType: "fluency",
      recommendationKey: "G1_NUMBER_SEQUENCE",
      misconceptionKey: "SEQUENCE_OFF_BY_ONE",
      diagnosticWeight: 1,
      diagnosticVersion: GRADE_1_DIAGNOSTIC_VERSION,
    },
  ),
  q(
    1,
    "v2-q08",
    "Pemahaman Bilangan",
    "sedang",
    "Urutkan 9, 12, dan 6 dari yang paling kecil ke paling besar.",
    ["9, 6, 12", "12, 9, 6", "6, 9, 12", "6, 12, 9"],
    "6, 9, 12",
    "6 adalah yang paling kecil, lalu 9, lalu 12.",
    {
      skillLevel: 1,
      assessmentBand: "core",
      domain: "Number Sense",
      skill: "Number Magnitude",
      subskill: "Ordering Numbers",
      prerequisiteSkill: "Compare Quantities",
      cognitiveType: "reasoning",
      recommendationKey: "G1_NUMBER_MAGNITUDE",
      misconceptionKey: "MAGNITUDE_REVERSAL",
      diagnosticWeight: 1,
      diagnosticVersion: GRADE_1_DIAGNOSTIC_VERSION,
    },
  ),
  q(
    1,
    "v2-q09",
    "Pemahaman Bilangan",
    "sedang",
    "13 = 10 + __. Angka yang tepat adalah ...",
    ["2", "3", "4", "5"],
    "3",
    "13 terdiri dari 10 dan 3.",
    {
      skillLevel: 1,
      assessmentBand: "core",
      domain: "Number Sense",
      skill: "Number Composition",
      subskill: "Teen Number Composition",
      prerequisiteSkill: "Part-Part-Whole within 10",
      cognitiveType: "concept",
      recommendationKey: "G1_NUMBER_COMPOSITION",
      misconceptionKey: "PART_WHOLE_CONFUSION",
      diagnosticWeight: 1,
      diagnosticVersion: GRADE_1_DIAGNOSTIC_VERSION,
    },
  ),
  q(
    1,
    "v2-q10",
    "Kelancaran Berhitung",
    "mudah",
    "6 + 3 = ...",
    ["8", "9", "10", "11"],
    "9",
    "6 + 3 = 9.",
    {
      skillLevel: 1,
      assessmentBand: "core",
      domain: "Operations",
      skill: "Addition",
      subskill: "Addition within 10",
      prerequisiteSkill: "Addition as Joining",
      cognitiveType: "fluency",
      recommendationKey: "G1_BASIC_ADDITION",
      diagnosticWeight: 1,
      diagnosticVersion: GRADE_1_DIAGNOSTIC_VERSION,
    },
  ),
  q(
    1,
    "v2-q11",
    "Kelancaran Berhitung",
    "mudah",
    "9 - 4 = ...",
    ["4", "5", "6", "7"],
    "5",
    "Jika 4 diambil dari 9, tersisa 5.",
    {
      skillLevel: 1,
      assessmentBand: "core",
      domain: "Operations",
      skill: "Subtraction",
      subskill: "Subtraction within 10",
      cognitiveType: "fluency",
      recommendationKey: "G1_BASIC_SUBTRACTION",
      diagnosticWeight: 1,
      diagnosticVersion: GRADE_1_DIAGNOSTIC_VERSION,
    },
  ),
  q(
    1,
    "v2-q12",
    "Kelancaran Berhitung",
    "sedang",
    "5 + __ = 8. Angka yang hilang adalah ...",
    ["2", "3", "4", "5"],
    "3",
    "5 + 3 = 8.",
    {
      skillLevel: 1,
      assessmentBand: "core",
      domain: "Relational Thinking",
      skill: "Missing Number",
      subskill: "Missing Addend",
      prerequisiteSkill: "Addition within 10",
      cognitiveType: "concept",
      recommendationKey: "G1_MISSING_ADDEND",
      misconceptionKey: "DIRECT_ONLY_ADDITION",
      diagnosticWeight: 1,
      diagnosticVersion: GRADE_1_DIAGNOSTIC_VERSION,
    },
  ),
  q(
    1,
    "v2-q13",
    "Kelancaran Berhitung",
    "menantang",
    "__ + 2 = 7. Angka yang hilang adalah ...",
    ["4", "5", "6", "7"],
    "5",
    "5 + 2 = 7.",
    {
      skillLevel: 1,
      assessmentBand: "core",
      domain: "Relational Thinking",
      skill: "Missing Number",
      subskill: "Unknown First Addend",
      prerequisiteSkill: "Addition within 10",
      cognitiveType: "reasoning",
      recommendationKey: "G1_MISSING_ADDEND",
      misconceptionKey: "DIRECT_ONLY_ADDITION",
      diagnosticWeight: 1,
      diagnosticVersion: GRADE_1_DIAGNOSTIC_VERSION,
    },
  ),
  q(
    1,
    "v2-q14",
    "Soal Cerita",
    "sedang",
    "Maya punya 4 pensil. Ibu memberi 3 pensil lagi. Berapa pensil Maya sekarang?",
    ["6", "7", "8", "9"],
    "7",
    "4 + 3 = 7 pensil.",
    {
      skillLevel: 1,
      assessmentBand: "core",
      domain: "Problem Solving",
      skill: "Addition Word Problem",
      subskill: "Add-to Situation",
      prerequisiteSkill: "Addition within 10",
      cognitiveType: "application",
      recommendationKey: "G1_WORD_PROBLEM",
      misconceptionKey: "OPERATION_SELECTION",
      diagnosticWeight: 1,
      diagnosticVersion: GRADE_1_DIAGNOSTIC_VERSION,
    },
  ),
  q(
    1,
    "v2-q15",
    "Soal Cerita",
    "sedang",
    "Rafi punya 8 balon. 3 balon terbang. Berapa balon yang tersisa?",
    ["4", "5", "6", "7"],
    "5",
    "8 - 3 = 5 balon.",
    {
      skillLevel: 1,
      assessmentBand: "core",
      domain: "Problem Solving",
      skill: "Subtraction Word Problem",
      subskill: "Take-away Situation",
      prerequisiteSkill: "Subtraction within 10",
      cognitiveType: "application",
      recommendationKey: "G1_WORD_PROBLEM",
      misconceptionKey: "OPERATION_SELECTION",
      diagnosticWeight: 1,
      diagnosticVersion: GRADE_1_DIAGNOSTIC_VERSION,
    },
  ),
  q(
    1,
    "v2-q16",
    "Penalaran Logis",
    "mudah",
    "Pensil A: ━━━━━━━━━━━  |  Pensil B: ━━━━━━. Pensil mana yang lebih panjang?",
    ["Pensil A", "Pensil B", "Sama panjang", "Tidak dapat ditentukan"],
    "Pensil A",
    "Garis Pensil A lebih panjang daripada Pensil B.",
    {
      skillLevel: 1,
      assessmentBand: "core",
      domain: "Measurement",
      skill: "Direct Length Comparison",
      subskill: "Compare Length Directly",
      cognitiveType: "concept",
      recommendationKey: "G1_MEASUREMENT",
      diagnosticWeight: 1,
      diagnosticVersion: GRADE_1_DIAGNOSTIC_VERSION,
    },
  ),
  q(
    1,
    "v2-q17",
    "Penalaran Logis",
    "sedang",
    "Bentuk mana yang memiliki 3 sisi?",
    ["○", "△", "□", "▭"],
    "△",
    "Segitiga memiliki 3 sisi.",
    {
      skillLevel: 1,
      assessmentBand: "core",
      domain: "Geometry",
      skill: "Shape Attributes",
      subskill: "Identify Shape by Number of Sides",
      cognitiveType: "concept",
      recommendationKey: "G1_SHAPE_ATTRIBUTES",
      misconceptionKey: "SHAPE_NAME_ONLY",
      diagnosticWeight: 1,
      diagnosticVersion: GRADE_1_DIAGNOSTIC_VERSION,
    },
  ),
  q(
    1,
    "v2-q18",
    "Penalaran Logis",
    "sedang",
    "🐱        📦  Posisi kucing terhadap kotak adalah ...",
    ["Di sebelah kiri", "Di sebelah kanan", "Di atas", "Di bawah"],
    "Di sebelah kiri",
    "Kucing berada di sebelah kiri kotak.",
    {
      skillLevel: 1,
      assessmentBand: "core",
      domain: "Geometry",
      skill: "Spatial Position",
      subskill: "Left and Right",
      cognitiveType: "concept",
      recommendationKey: "G1_SPATIAL_POSITION",
      diagnosticWeight: 1,
      diagnosticVersion: GRADE_1_DIAGNOSTIC_VERSION,
    },
  ),
  q(
    1,
    "v2-q19",
    "Pemahaman Bilangan",
    "sedang",
    "Bilangan 24 terdiri dari ...",
    [
      "2 puluhan dan 4 satuan",
      "4 puluhan dan 2 satuan",
      "2 puluhan dan 2 satuan",
      "4 puluhan dan 4 satuan",
    ],
    "2 puluhan dan 4 satuan",
    "24 terdiri dari 2 puluhan dan 4 satuan.",
    {
      skillLevel: 2,
      assessmentBand: "stretch",
      domain: "Number Sense",
      skill: "Place Value",
      subskill: "Tens and Ones",
      prerequisiteSkill: "Teen Number Composition",
      cognitiveType: "concept",
      recommendationKey: "G1_PLACE_VALUE",
      misconceptionKey: "REVERSED_TENS_ONES",
      diagnosticWeight: 1,
      diagnosticVersion: GRADE_1_DIAGNOSTIC_VERSION,
    },
  ),
  q(
    1,
    "v2-q20",
    "Kelancaran Berhitung",
    "menantang",
    "13 + 5 = ...",
    ["16", "17", "18", "19"],
    "18",
    "13 + 5 = 18.",
    {
      skillLevel: 2,
      assessmentBand: "stretch",
      domain: "Operations",
      skill: "Addition",
      subskill: "Addition within 20",
      prerequisiteSkill: "Addition within 10",
      cognitiveType: "fluency",
      recommendationKey: "G1_BASIC_ADDITION",
      diagnosticWeight: 1,
      diagnosticVersion: GRADE_1_DIAGNOSTIC_VERSION,
    },
  ),
  q(
    1,
    "v2-q21",
    "Kelancaran Berhitung",
    "menantang",
    "17 - 6 = ...",
    ["10", "11", "12", "13"],
    "11",
    "17 - 6 = 11.",
    {
      skillLevel: 2,
      assessmentBand: "stretch",
      domain: "Operations",
      skill: "Subtraction",
      subskill: "Subtraction within 20",
      prerequisiteSkill: "Subtraction within 10",
      cognitiveType: "fluency",
      recommendationKey: "G1_BASIC_SUBTRACTION",
      diagnosticWeight: 1,
      diagnosticVersion: GRADE_1_DIAGNOSTIC_VERSION,
    },
  ),
  q(
    1,
    "v2-q22",
    "Pecahan",
    "sedang",
    "Ada 2 lingkaran. 1 lingkaran berwarna hijau.\n{{circle-green:1}} {{circle:1}}\nBagian yang berwarna hijau adalah ...",
    [
      "1 dari 2 = \frac{1}{2}",
      "1 dari 3 = \frac{1}{3}",
      "1 dari 4 = \frac{1}{4}",
      "2 dari 2 = \frac{2}{2}",
    ],
    "1 dari 2 = \\frac{1}{2}",
    "gambar disamping termasuk pecahan ?",
    {
      skillLevel: 2,
      assessmentBand: "stretch",
      domain: "Fractions",
      skill: "Fraction as Part of a Whole",
      subskill: "One Half",
      prerequisiteSkill: "Equal Parts",
      cognitiveType: "concept",
      recommendationKey: "G1_FRACTION_FOUNDATION",
      misconceptionKey: "FRACTION_EQUAL_PARTS",
      diagnosticWeight: 1,
      diagnosticVersion: GRADE_1_DIAGNOSTIC_VERSION,
    },
  ),
  q(
    1,
    "v2-q23",
    "Penalaran Logis",
    "sedang",
    "Apel: ★★★★  |  Pisang: ★★  |  Jeruk: ★★★. Buah mana yang memiliki tanda paling banyak?",
    ["Apel", "Pisang", "Jeruk", "Sama banyak"],
    "Apel",
    "Apel memiliki 4 tanda, paling banyak dibandingkan yang lain.",
    {
      skillLevel: 2,
      assessmentBand: "stretch",
      domain: "Data",
      skill: "Interpret Simple Data",
      subskill: "Compare Pictograph Counts",
      prerequisiteSkill: "Compare Quantities",
      cognitiveType: "application",
      recommendationKey: "G1_DATA_INTERPRETATION",
      diagnosticWeight: 1,
      diagnosticVersion: GRADE_1_DIAGNOSTIC_VERSION,
    },
  ),
  q(
    1,
    "v2-q24",
    "Soal Cerita",
    "menantang",
    "Lina punya 7 stiker. Ia mendapat 5 stiker lagi. Berapa stiker Lina sekarang?",
    ["11", "12", "13", "14"],
    "12",
    "7 + 5 = 12 stiker.",
    {
      skillLevel: 2,
      assessmentBand: "stretch",
      domain: "Problem Solving",
      skill: "Addition Word Problem",
      subskill: "Transfer within 20",
      prerequisiteSkill: "Addition within 10",
      cognitiveType: "application",
      recommendationKey: "G1_WORD_PROBLEM",
      misconceptionKey: "OPERATION_SELECTION",
      diagnosticWeight: 1,
      diagnosticVersion: GRADE_1_DIAGNOSTIC_VERSION,
    },
  ),
];

const banks: Record<number, DiagnosticQuestion[]> = {
  1: [
    q(
      1,
      "n1",
      "Pemahaman Bilangan",
      "mudah",
      "Bilangan setelah 18 adalah ...",
      ["17", "19", "20", "28"],
      "19",
      "Urutan bilangan adalah 17, 18, 19, 20.",
    ),
    q(
      1,
      "n2",
      "Pemahaman Bilangan",
      "mudah",
      "Mana bilangan yang paling besar?",
      ["12", "21", "19", "16"],
      "21",
      "Bilangan 21 lebih besar daripada 19, 16, dan 12.",
    ),
    q(
      1,
      "a1",
      "Kelancaran Berhitung",
      "mudah",
      "7 + 5 = ...",
      ["10", "11", "12", "13"],
      "12",
      "7 + 5 = 12.",
    ),
    q(
      1,
      "a2",
      "Kelancaran Berhitung",
      "sedang",
      "15 - 8 = ...",
      ["6", "7", "8", "9"],
      "7",
      "15 dikurangi 8 tersisa 7.",
    ),
    q(
      1,
      "w1",
      "Soal Cerita",
      "sedang",
      "Rani punya 6 apel. Ibu memberi 4 apel lagi. Jumlah apel Rani sekarang ...",
      ["8", "9", "10", "11"],
      "10",
      "6 apel + 4 apel = 10 apel.",
    ),
    q(
      1,
      "l1",
      "Penalaran Logis",
      "sedang",
      "Pola: 2, 4, 6, 8, ...",
      ["9", "10", "11", "12"],
      "10",
      "Pola bertambah 2, jadi setelah 8 adalah 10.",
    ),
    q(
      1,
      "n3",
      "Pemahaman Bilangan",
      "mudah",
      "Angka 3 pada bilangan 13 bernilai ...",
      ["3", "10", "13", "30"],
      "3",
      "Pada 13, angka 3 berada di satuan.",
    ),
    q(
      1,
      "a3",
      "Kelancaran Berhitung",
      "sedang",
      "9 + 8 = ...",
      ["15", "16", "17", "18"],
      "17",
      "9 + 8 = 17.",
    ),
  ],
  2: [
    q(
      2,
      "n1",
      "Pemahaman Bilangan",
      "mudah",
      "Bilangan 346 dibaca ...",
      [
        "tiga empat enam",
        "tiga ratus empat puluh enam",
        "tiga ratus enam puluh empat",
        "empat ratus tiga puluh enam",
      ],
      "tiga ratus empat puluh enam",
      "346 terdiri dari 3 ratusan, 4 puluhan, dan 6 satuan.",
    ),
    q(
      2,
      "n2",
      "Pemahaman Bilangan",
      "sedang",
      "Nilai angka 7 pada 274 adalah ...",
      ["7", "70", "700", "270"],
      "70",
      "Angka 7 berada pada tempat puluhan.",
    ),
    q(
      2,
      "a1",
      "Kelancaran Berhitung",
      "mudah",
      "48 + 27 = ...",
      ["65", "75", "76", "85"],
      "75",
      "48 + 27 = 75.",
    ),
    q(
      2,
      "a2",
      "Kelancaran Berhitung",
      "sedang",
      "92 - 38 = ...",
      ["44", "54", "56", "64"],
      "54",
      "92 - 38 = 54.",
    ),
    q(
      2,
      "w1",
      "Soal Cerita",
      "sedang",
      "Ada 3 kotak. Setiap kotak berisi 6 pensil. Jumlah pensil seluruhnya ...",
      ["9", "12", "18", "36"],
      "18",
      "3 kelompok berisi 6 berarti 3 x 6 = 18.",
    ),
    q(
      2,
      "l1",
      "Penalaran Logis",
      "sedang",
      "Pola: 5, 10, 15, 20, ...",
      ["21", "24", "25", "30"],
      "25",
      "Pola bertambah 5.",
    ),
    q(
      2,
      "f1",
      "Pecahan",
      "sedang",
      "Setengah dari 10 adalah ...",
      ["2", "4", "5", "8"],
      "5",
      "Setengah berarti dibagi 2, jadi 10 : 2 = 5.",
    ),
    q(
      2,
      "a3",
      "Kelancaran Berhitung",
      "menantang",
      "6 x 4 + 5 = ...",
      ["24", "25", "29", "35"],
      "29",
      "Kerjakan perkalian dulu: 6 x 4 = 24, lalu 24 + 5 = 29.",
    ),
  ],
  3: [
    q(
      3,
      "n1",
      "Pemahaman Bilangan",
      "mudah",
      "Bilangan 4.508 memiliki ... ribuan.",
      ["4", "5", "8", "508"],
      "4",
      "Angka 4 berada pada tempat ribuan.",
    ),
    q(
      3,
      "a1",
      "Kelancaran Berhitung",
      "mudah",
      "235 + 418 = ...",
      ["643", "653", "663", "753"],
      "653",
      "235 + 418 = 653.",
    ),
    q(
      3,
      "a2",
      "Kelancaran Berhitung",
      "sedang",
      "72 : 8 = ...",
      ["7", "8", "9", "10"],
      "9",
      "8 x 9 = 72, jadi 72 : 8 = 9.",
    ),
    q(
      3,
      "f1",
      "Pecahan",
      "sedang",
      "Pecahan yang lebih besar adalah ...",
      ["\\frac{1}{2}", "\\frac{1}{4}", "\\frac{1}{8}", "\\frac{1}{10}"],
      "\\frac{1}{2}",
      "Untuk pembilang sama, penyebut lebih kecil berarti nilai pecahan lebih besar.",
    ),
    q(
      3,
      "w1",
      "Soal Cerita",
      "sedang",
      "Budi membeli 4 bungkus roti. Tiap bungkus berisi 5 roti. Ia makan 3 roti. Sisa roti ...",
      ["17", "18", "20", "23"],
      "17",
      "4 x 5 = 20 roti, lalu 20 - 3 = 17.",
    ),
    q(
      3,
      "l1",
      "Penalaran Logis",
      "sedang",
      "Pola: 3, 6, 12, 24, ...",
      ["30", "36", "42", "48"],
      "48",
      "Pola dikali 2.",
    ),
    q(
      3,
      "a3",
      "Kelancaran Berhitung",
      "menantang",
      "125 x 4 = ...",
      ["400", "450", "500", "550"],
      "500",
      "125 x 4 = 500.",
    ),
    q(
      3,
      "w2",
      "Soal Cerita",
      "menantang",
      "Sebuah tali 90 cm dipotong menjadi 3 bagian sama panjang. Panjang tiap bagian ...",
      ["20 cm", "25 cm", "30 cm", "35 cm"],
      "30 cm",
      "90 : 3 = 30 cm.",
    ),
  ],
  4: [
    q(
      4,
      "n1",
      "Pemahaman Bilangan",
      "mudah",
      "Nilai angka 6 pada 36.245 adalah ...",
      ["6", "60", "6.000", "60.000"],
      "6.000",
      "Angka 6 berada pada tempat ribuan.",
    ),
    q(
      4,
      "a1",
      "Kelancaran Berhitung",
      "sedang",
      "2.408 + 1.795 = ...",
      ["4.103", "4.203", "4.303", "4.403"],
      "4.203",
      "2.408 + 1.795 = 4.203.",
    ),
    q(
      4,
      "a2",
      "Kelancaran Berhitung",
      "sedang",
      "324 : 6 = ...",
      ["44", "52", "54", "64"],
      "54",
      "6 x 54 = 324.",
    ),
    q(
      4,
      "f1",
      "Pecahan",
      "sedang",
      "\\frac{1}{4} + \\frac{2}{4} = ...",
      ["\\frac{1}{4}", "\\frac{2}{4}", "\\frac{3}{4}", "\\frac{4}{8}"],
      "\\frac{3}{4}",
      "Penyebut sama, jumlahkan pembilang: 1 + 2 = 3.",
    ),
    q(
      4,
      "w1",
      "Soal Cerita",
      "sedang",
      "Satu buku harganya Rp8.000. Dika membeli 3 buku dan membayar Rp30.000. Kembaliannya ...",
      ["Rp4.000", "Rp5.000", "Rp6.000", "Rp8.000"],
      "Rp6.000",
      "3 x 8.000 = 24.000, kembaliannya 30.000 - 24.000 = 6.000.",
    ),
    q(
      4,
      "l1",
      "Penalaran Logis",
      "menantang",
      "Pola: 2, 5, 11, 23, ...",
      ["35", "41", "47", "49"],
      "47",
      "Pola dikali 2 lalu tambah 1: 23 x 2 + 1 = 47.",
    ),
    q(
      4,
      "f2",
      "Pecahan",
      "menantang",
      "Pecahan senilai dengan \\frac{2}{3} adalah ...",
      ["\\frac{3}{4}", "\\frac{4}{6}", "\\frac{5}{6}", "\\frac{6}{8}"],
      "\\frac{4}{6}",
      "\\frac{2}{3} dikali 2/2 menjadi \\frac{4}{6}.",
    ),
    q(
      4,
      "w2",
      "Soal Cerita",
      "menantang",
      "Luas persegi dengan sisi 9 cm adalah ...",
      ["18 cm^2", "36 cm^2", "81 cm^2", "90 cm^2"],
      "81 cm^2",
      "Luas persegi = sisi x sisi = 9 x 9 = 81 cm^2.",
    ),
  ],
  5: [
    q(
      5,
      "n1",
      "Pemahaman Bilangan",
      "sedang",
      "Bilangan 75.320 jika dibulatkan ke ribuan terdekat menjadi ...",
      ["75.000", "76.000", "75.300", "80.000"],
      "75.000",
      "Angka ratusannya 3, jadi tetap 75.000.",
    ),
    q(
      5,
      "a1",
      "Kelancaran Berhitung",
      "sedang",
      "125 x 16 = ...",
      ["1.500", "1.750", "2.000", "2.250"],
      "2.000",
      "125 x 16 = 125 x 8 x 2 = 1.000 x 2 = 2.000.",
    ),
    q(
      5,
      "a2",
      "Kelancaran Berhitung",
      "sedang",
      "1.248 : 12 = ...",
      ["94", "104", "114", "124"],
      "104",
      "12 x 104 = 1.248.",
    ),
    q(
      5,
      "f1",
      "Pecahan",
      "sedang",
      "\\frac{3}{5} + \\frac{1}{10} = ...",
      ["\\frac{4}{15}", "\\frac{4}{10}", "\\frac{7}{10}", "\\frac{8}{10}"],
      "\\frac{7}{10}",
      "\\frac{3}{5} = \\frac{6}{10}, lalu \\frac{6}{10} + \\frac{1}{10} = \\frac{7}{10}.",
    ),
    q(
      5,
      "f2",
      "Pecahan",
      "menantang",
      "0,75 sama dengan ...",
      ["\\frac{1}{4}", "\\frac{1}{2}", "\\frac{3}{4}", "\\frac{4}{3}"],
      "\\frac{3}{4}",
      "0,75 = 75/100 = 3/4.",
    ),
    q(
      5,
      "w1",
      "Soal Cerita",
      "sedang",
      "Sebuah kelas memiliki 32 siswa. \\frac{3}{8} siswa mengikuti klub matematika. Jumlahnya ...",
      ["8", "10", "12", "14"],
      "12",
      "\\frac{3}{8} dari 32 = 32 : 8 x 3 = 12.",
    ),
    q(
      5,
      "l1",
      "Penalaran Logis",
      "menantang",
      "Jika 3 kotak = 24, maka 5 kotak = ...",
      ["32", "36", "40", "45"],
      "40",
      "1 kotak = 24 : 3 = 8, jadi 5 kotak = 40.",
    ),
    q(
      5,
      "w2",
      "Soal Cerita",
      "menantang",
      "Luas persegi panjang 12 cm x 8 cm adalah ...",
      ["20 cm^2", "40 cm^2", "80 cm^2", "96 cm^2"],
      "96 cm^2",
      "Luas = panjang x lebar = 12 x 8 = 96 cm^2.",
    ),
  ],
  6: [
    q(
      6,
      "n1",
      "Pemahaman Bilangan",
      "sedang",
      "FPB dari 24 dan 36 adalah ...",
      ["6", "8", "12", "18"],
      "12",
      "Faktor terbesar yang sama dari 24 dan 36 adalah 12.",
    ),
    q(
      6,
      "a1",
      "Kelancaran Berhitung",
      "sedang",
      "2^3 + 5^2 = ...",
      ["13", "25", "33", "38"],
      "33",
      "2^3 = 8 dan 5^2 = 25, jadi totalnya 33.",
    ),
    q(
      6,
      "a2",
      "Kelancaran Berhitung",
      "menantang",
      "15% dari 240 adalah ...",
      ["24", "30", "36", "42"],
      "36",
      "10% dari 240 = 24 dan 5% = 12, total 36.",
    ),
    q(
      6,
      "f1",
      "Pecahan",
      "sedang",
      "\\frac{2}{3} x 18 = ...",
      ["6", "9", "12", "15"],
      "12",
      "18 : 3 x 2 = 12.",
    ),
    q(
      6,
      "f2",
      "Pecahan",
      "menantang",
      "\\frac{5}{6} - \\frac{1}{3} = ...",
      ["\\frac{1}{6}", "\\frac{2}{6}", "\\frac{3}{6}", "\\frac{4}{6}"],
      "\\frac{3}{6}",
      "\\frac{1}{3} = \\frac{2}{6}, jadi \\frac{5}{6} - \\frac{2}{6} = \\frac{3}{6}.",
    ),
    q(
      6,
      "w1",
      "Soal Cerita",
      "sedang",
      "Harga tas Rp120.000 diskon 25%. Besar diskon adalah ...",
      ["Rp20.000", "Rp25.000", "Rp30.000", "Rp40.000"],
      "Rp30.000",
      "25% = 1/4, jadi diskon = 120.000 : 4 = 30.000.",
    ),
    q(
      6,
      "l1",
      "Penalaran Logis",
      "menantang",
      "Pola: 1, 4, 9, 16, ...",
      ["20", "24", "25", "36"],
      "25",
      "Pola bilangan kuadrat: 1^2, 2^2, 3^2, 4^2, maka berikutnya 5^2 = 25.",
    ),
    q(
      6,
      "w2",
      "Soal Cerita",
      "menantang",
      "Volume kubus dengan rusuk 5 cm adalah ...",
      ["15 cm^3", "25 cm^3", "75 cm^3", "125 cm^3"],
      "125 cm^3",
      "Volume kubus = s^3 = 5^3 = 125 cm^3.",
    ),
  ],
};

function makeSecondaryGradeBank(gradeLevel: number): DiagnosticQuestion[] {
  const g = Math.min(12, Math.max(7, gradeLevel));
  const common: Record<number, DiagnosticQuestion[]> = {
    7: [
      q(
        7,
        "n1",
        "Pemahaman Bilangan",
        "sedang",
        "Hasil dari -18 + 25 - 9 adalah ...",
        ["-2", "-1", "2", "16"],
        "-2",
        "Hitung berurutan: -18 + 25 = 7, lalu 7 - 9 = -2.",
      ),
      q(
        7,
        "n2",
        "Pemahaman Bilangan",
        "sedang",
        "Urutan dari terkecil adalah ...",
        ["-3, -1, 2, 5", "5, 2, -1, -3", "-1, -3, 2, 5", "2, 5, -3, -1"],
        "-3, -1, 2, 5",
        "Pada garis bilangan, bilangan yang lebih kiri nilainya lebih kecil.",
      ),
      q(
        7,
        "n3",
        "Pemahaman Bilangan",
        "menantang",
        "Bentuk desimal dari \\frac{3}{8} adalah ...",
        ["0,125", "0,25", "0,375", "0,625"],
        "0,375",
        "3 : 8 = 0,375.",
      ),
      q(
        7,
        "n4",
        "Pemahaman Bilangan",
        "sedang",
        "Perbandingan 24 : 36 disederhanakan menjadi ...",
        ["2 : 3", "3 : 2", "4 : 5", "6 : 9"],
        "2 : 3",
        "24 dan 36 dibagi FPB 12 menjadi 2 : 3.",
      ),
      q(
        7,
        "a1",
        "Kelancaran Berhitung",
        "sedang",
        "\\frac{2}{3} + \\frac{1}{6} = ...",
        ["\\frac{3}{9}", "\\frac{1}{2}", "\\frac{5}{6}", "1"],
        "\\frac{5}{6}",
        "Samakan penyebut: 2/3 = 4/6, lalu 4/6 + 1/6 = 5/6.",
      ),
      q(
        7,
        "a2",
        "Kelancaran Berhitung",
        "sedang",
        "0,4 x 2,5 = ...",
        ["0,1", "1", "10", "100"],
        "1",
        "0,4 x 2,5 = 1,0.",
      ),
      q(
        7,
        "a3",
        "Kelancaran Berhitung",
        "menantang",
        "Hasil dari 3^2 + 2^3 - 5 adalah ...",
        ["8", "10", "12", "17"],
        "12",
        "3^2 = 9 dan 2^3 = 8, jadi 9 + 8 - 5 = 12.",
      ),
      q(
        7,
        "a4",
        "Kelancaran Berhitung",
        "menantang",
        "Jika x = -4, nilai 3x + 10 adalah ...",
        ["-22", "-2", "2", "22"],
        "-2",
        "3(-4) + 10 = -12 + 10 = -2.",
      ),
      q(
        7,
        "f1",
        "Pecahan",
        "sedang",
        "\\frac{5}{6} - \\frac{1}{4} = ...",
        ["\\frac{4}{2}", "\\frac{7}{12}", "\\frac{2}{12}", "\\frac{6}{10}"],
        "\\frac{7}{12}",
        "5/6 = 10/12 dan 1/4 = 3/12, selisihnya 7/12.",
      ),
      q(
        7,
        "f2",
        "Pecahan",
        "menantang",
        "\\frac{3}{5} dari 150 adalah ...",
        ["60", "75", "90", "120"],
        "90",
        "150 : 5 x 3 = 90.",
      ),
      q(
        7,
        "f3",
        "Pecahan",
        "sedang",
        "Pecahan senilai dengan 0,6 adalah ...",
        ["\\frac{3}{5}", "\\frac{2}{5}", "\\frac{6}{100}", "\\frac{5}{3}"],
        "\\frac{3}{5}",
        "0,6 = 6/10 = 3/5.",
      ),
      q(
        7,
        "f4",
        "Pecahan",
        "menantang",
        "\\frac{2}{3} : \\frac{4}{9} = ...",
        ["\\frac{8}{27}", "\\frac{3}{2}", "\\frac{6}{7}", "\\frac{2}{9}"],
        "\\frac{3}{2}",
        "Pembagian pecahan dikali kebalikan: 2/3 x 9/4 = 18/12 = 3/2.",
      ),
      q(
        7,
        "w1",
        "Soal Cerita",
        "sedang",
        "Harga 5 buku Rp40.000. Harga 8 buku adalah ...",
        ["Rp56.000", "Rp64.000", "Rp72.000", "Rp80.000"],
        "Rp64.000",
        "Harga 1 buku = 40.000 : 5 = 8.000, maka 8 buku = 64.000.",
      ),
      q(
        7,
        "w2",
        "Soal Cerita",
        "menantang",
        "Skala peta 1 : 200.000. Jarak pada peta 4 cm. Jarak sebenarnya ...",
        ["4 km", "6 km", "8 km", "12 km"],
        "8 km",
        "4 x 200.000 cm = 800.000 cm = 8 km.",
      ),
      q(
        7,
        "w3",
        "Soal Cerita",
        "sedang",
        "Dalam 3 jam, keran mengisi 45 liter air. Dalam 7 jam, air yang terisi ...",
        ["90 liter", "105 liter", "120 liter", "135 liter"],
        "105 liter",
        "Debit = 45 : 3 = 15 liter/jam, maka 7 jam = 105 liter.",
      ),
      q(
        7,
        "w4",
        "Soal Cerita",
        "menantang",
        "Perbandingan uang Ani dan Budi 3 : 5. Jumlah uang mereka Rp96.000. Uang Budi ...",
        ["Rp36.000", "Rp48.000", "Rp60.000", "Rp72.000"],
        "Rp60.000",
        "Total bagian 8. Budi = 5/8 x 96.000 = 60.000.",
      ),
      q(
        7,
        "l1",
        "Penalaran Logis",
        "sedang",
        "Pola 4, 7, 13, 25, ... berlanjut dengan ...",
        ["37", "43", "49", "51"],
        "49",
        "Selisihnya 3, 6, 12, sehingga selanjutnya tambah 24 menjadi 49.",
      ),
      q(
        7,
        "l2",
        "Penalaran Logis",
        "menantang",
        "Jika a * b = 2a + b, maka 4 * 7 = ...",
        ["11", "14", "15", "18"],
        "15",
        "2(4) + 7 = 15.",
      ),
      q(
        7,
        "l3",
        "Penalaran Logis",
        "sedang",
        "Sudut pelurus dari 68 derajat adalah ...",
        ["22 derajat", "68 derajat", "112 derajat", "122 derajat"],
        "112 derajat",
        "Sudut pelurus berjumlah 180 derajat, jadi 180 - 68 = 112.",
      ),
      q(
        7,
        "l4",
        "Penalaran Logis",
        "menantang",
        "Keliling persegi 48 cm. Luasnya adalah ...",
        ["96 cm^2", "120 cm^2", "144 cm^2", "192 cm^2"],
        "144 cm^2",
        "Sisi = 48 : 4 = 12 cm, luas = 12 x 12 = 144 cm^2.",
      ),
    ],
    8: [
      q(
        8,
        "n1",
        "Pemahaman Bilangan",
        "sedang",
        "Bentuk sederhana dari 2^3 x 2^4 adalah ...",
        ["2^7", "2^12", "4^7", "4^12"],
        "2^7",
        "Jika basis sama dikalikan, pangkat dijumlahkan: 3 + 4 = 7.",
      ),
      q(
        8,
        "n2",
        "Pemahaman Bilangan",
        "sedang",
        "Akar kuadrat dari 196 adalah ...",
        ["12", "13", "14", "16"],
        "14",
        "14 x 14 = 196.",
      ),
      q(
        8,
        "n3",
        "Pemahaman Bilangan",
        "menantang",
        "Notasi ilmiah dari 45.000 adalah ...",
        ["4,5 x 10^3", "4,5 x 10^4", "45 x 10^4", "0,45 x 10^5"],
        "4,5 x 10^4",
        "45.000 = 4,5 x 10.000 = 4,5 x 10^4.",
      ),
      q(
        8,
        "n4",
        "Pemahaman Bilangan",
        "sedang",
        "Nilai dari 3^-2 adalah ...",
        ["-9", "-6", "\\frac{1}{9}", "\\frac{1}{6}"],
        "\\frac{1}{9}",
        "Pangkat negatif berarti kebalikan: 3^-2 = 1/3^2 = 1/9.",
      ),
      q(
        8,
        "a1",
        "Kelancaran Berhitung",
        "sedang",
        "Jika 4x - 7 = 21, maka x = ...",
        ["5", "6", "7", "8"],
        "7",
        "4x = 28, jadi x = 7.",
      ),
      q(
        8,
        "a2",
        "Kelancaran Berhitung",
        "menantang",
        "Hasil dari (2x + 3) + (5x - 8) adalah ...",
        ["7x - 5", "7x + 5", "3x - 11", "10x - 24"],
        "7x - 5",
        "Gabungkan suku sejenis: 2x + 5x = 7x dan 3 - 8 = -5.",
      ),
      q(
        8,
        "a3",
        "Kelancaran Berhitung",
        "sedang",
        "Gradien garis melalui (1, 3) dan (5, 11) adalah ...",
        ["1", "2", "3", "4"],
        "2",
        "Gradien = (11 - 3) / (5 - 1) = 8/4 = 2.",
      ),
      q(
        8,
        "a4",
        "Kelancaran Berhitung",
        "menantang",
        "Persamaan garis dengan gradien 3 melalui (0, 2) adalah ...",
        ["y = 3x + 2", "y = 2x + 3", "y = 3x - 2", "y = -3x + 2"],
        "y = 3x + 2",
        "Bentuk y = mx + c. Gradien 3 dan titik potong y 2, jadi y = 3x + 2.",
      ),
      q(
        8,
        "f1",
        "Pecahan",
        "sedang",
        "0,375 dalam bentuk pecahan sederhana adalah ...",
        ["\\frac{3}{8}", "\\frac{5}{8}", "\\frac{3}{5}", "\\frac{8}{3}"],
        "\\frac{3}{8}",
        "0,375 = 375/1000 = 3/8.",
      ),
      q(
        8,
        "f2",
        "Pecahan",
        "menantang",
        "\\frac{2x}{3} = 10, maka x = ...",
        ["12", "15", "18", "20"],
        "15",
        "Kalikan 3: 2x = 30, maka x = 15.",
      ),
      q(
        8,
        "f3",
        "Pecahan",
        "sedang",
        "75% dari 320 adalah ...",
        ["220", "230", "240", "250"],
        "240",
        "75% = 3/4, jadi 320 x 3/4 = 240.",
      ),
      q(
        8,
        "f4",
        "Pecahan",
        "menantang",
        "\\frac{5}{8} + 0,25 = ...",
        ["\\frac{6}{8}", "\\frac{7}{8}", "\\frac{8}{8}", "\\frac{9}{8}"],
        "\\frac{7}{8}",
        "0,25 = 1/4 = 2/8, jadi 5/8 + 2/8 = 7/8.",
      ),
      q(
        8,
        "w1",
        "Soal Cerita",
        "sedang",
        "Sebuah fungsi f(x)=2x+5. Nilai f(7) adalah ...",
        ["14", "17", "19", "24"],
        "19",
        "f(7) = 2(7) + 5 = 19.",
      ),
      q(
        8,
        "w2",
        "Soal Cerita",
        "menantang",
        "Harga 3 pensil dan 2 buku Rp19.000. Jika pensil Rp3.000, harga 1 buku ...",
        ["Rp4.000", "Rp5.000", "Rp6.000", "Rp7.000"],
        "Rp5.000",
        "3 pensil = 9.000, sisa 10.000 untuk 2 buku, jadi 1 buku 5.000.",
      ),
      q(
        8,
        "w3",
        "Soal Cerita",
        "sedang",
        "Luas segitiga alas 14 cm dan tinggi 9 cm adalah ...",
        ["63 cm^2", "72 cm^2", "126 cm^2", "144 cm^2"],
        "63 cm^2",
        "Luas segitiga = 1/2 x 14 x 9 = 63 cm^2.",
      ),
      q(
        8,
        "w4",
        "Soal Cerita",
        "menantang",
        "Volume prisma dengan luas alas 24 cm^2 dan tinggi 15 cm adalah ...",
        ["240 cm^3", "300 cm^3", "360 cm^3", "390 cm^3"],
        "360 cm^3",
        "Volume prisma = luas alas x tinggi = 24 x 15 = 360 cm^3.",
      ),
      q(
        8,
        "l1",
        "Penalaran Logis",
        "sedang",
        "Pola 1, 4, 9, 16, 25, ... adalah ...",
        ["30", "32", "36", "49"],
        "36",
        "Itu pola kuadrat: 1^2, 2^2, ..., berikutnya 6^2 = 36.",
      ),
      q(
        8,
        "l2",
        "Penalaran Logis",
        "menantang",
        "Jika y = 2x + 1, ketika x naik 3 maka y naik ...",
        ["3", "4", "6", "7"],
        "6",
        "Koefisien x adalah 2, jadi kenaikan y = 2 x 3 = 6.",
      ),
      q(
        8,
        "l3",
        "Penalaran Logis",
        "sedang",
        "Jumlah sudut dalam segitiga adalah ...",
        ["90 derajat", "120 derajat", "180 derajat", "360 derajat"],
        "180 derajat",
        "Jumlah sudut dalam setiap segitiga adalah 180 derajat.",
      ),
      q(
        8,
        "l4",
        "Penalaran Logis",
        "menantang",
        "Jika dua bangun sebangun dan skala sisi 2 : 5, maka perbandingan luasnya ...",
        ["2 : 5", "4 : 10", "4 : 25", "8 : 125"],
        "4 : 25",
        "Perbandingan luas adalah kuadrat perbandingan sisi, jadi 2^2 : 5^2 = 4 : 25.",
      ),
    ],
  };

  if (common[g]) return common[g];

  if (g === 9) {
    return [
      q(
        9,
        "n1",
        "Pemahaman Bilangan",
        "sedang",
        "Hasil dari \\sqrt{144} + \\sqrt{81} adalah ...",
        ["15", "18", "21", "24"],
        "21",
        "Akar 144 = 12 dan akar 81 = 9, total 21.",
      ),
      q(
        9,
        "n2",
        "Pemahaman Bilangan",
        "sedang",
        "Bentuk sederhana dari 6a - 2a + 5 adalah ...",
        ["3a + 5", "4a + 5", "8a + 5", "4a - 5"],
        "4a + 5",
        "Suku sejenis 6a - 2a = 4a.",
      ),
      q(
        9,
        "n3",
        "Pemahaman Bilangan",
        "menantang",
        "Jika a:b = 4:7 dan a = 28, maka b = ...",
        ["35", "42", "49", "56"],
        "49",
        "1 bagian = 28 : 4 = 7, maka b = 7 x 7 = 49.",
      ),
      q(
        9,
        "n4",
        "Pemahaman Bilangan",
        "sedang",
        "Bentuk faktor dari x^2 - 9 adalah ...",
        ["(x - 3)(x + 3)", "(x - 9)(x + 1)", "(x + 9)(x - 1)", "(x - 3)^2"],
        "(x - 3)(x + 3)",
        "x^2 - 9 adalah selisih kuadrat: x^2 - 3^2.",
      ),
      q(
        9,
        "a1",
        "Kelancaran Berhitung",
        "sedang",
        "Penyelesaian 2x + 3y = 19 dan x = 5 adalah y = ...",
        ["2", "3", "4", "5"],
        "3",
        "2(5) + 3y = 19, maka 3y = 9 dan y = 3.",
      ),
      q(
        9,
        "a2",
        "Kelancaran Berhitung",
        "menantang",
        "Jika 3x + 2y = 18 dan x = 4, maka y = ...",
        ["1", "2", "3", "4"],
        "3",
        "12 + 2y = 18, maka 2y = 6 dan y = 3.",
      ),
      q(
        9,
        "a3",
        "Kelancaran Berhitung",
        "sedang",
        "Gradien garis y = -2x + 7 adalah ...",
        ["-7", "-2", "2", "7"],
        "-2",
        "Pada y = mx + c, gradien adalah m.",
      ),
      q(
        9,
        "a4",
        "Kelancaran Berhitung",
        "menantang",
        "Akar dari x^2 - 5x + 6 = 0 adalah ...",
        ["1 dan 6", "2 dan 3", "-2 dan -3", "3 dan 5"],
        "2 dan 3",
        "Faktornya (x - 2)(x - 3) = 0.",
      ),
      q(
        9,
        "f1",
        "Pecahan",
        "sedang",
        "\\frac{x}{5} = 6, maka x = ...",
        ["11", "20", "25", "30"],
        "30",
        "x = 6 x 5 = 30.",
      ),
      q(
        9,
        "f2",
        "Pecahan",
        "menantang",
        "\\frac{2}{3}x + 4 = 12, maka x = ...",
        ["8", "10", "12", "14"],
        "12",
        "2/3 x = 8, maka x = 8 x 3/2 = 12.",
      ),
      q(
        9,
        "f3",
        "Pecahan",
        "sedang",
        "Peluang muncul angka genap pada dadu adalah ...",
        ["\\frac{1}{6}", "\\frac{1}{3}", "\\frac{1}{2}", "\\frac{2}{3}"],
        "\\frac{1}{2}",
        "Angka genap ada 3 dari 6 kemungkinan, jadi 3/6 = 1/2.",
      ),
      q(
        9,
        "f4",
        "Pecahan",
        "menantang",
        "Jika 40% dari suatu bilangan adalah 28, bilangannya ...",
        ["56", "60", "70", "80"],
        "70",
        "40% = 0,4, maka bilangan = 28 : 0,4 = 70.",
      ),
      q(
        9,
        "w1",
        "Soal Cerita",
        "sedang",
        "Jumlah dua bilangan 30 dan selisihnya 6. Bilangan terbesar adalah ...",
        ["12", "15", "18", "24"],
        "18",
        "Bilangan besar = (30 + 6) : 2 = 18.",
      ),
      q(
        9,
        "w2",
        "Soal Cerita",
        "menantang",
        "Sebuah tabung berjari-jari 7 cm dan tinggi 10 cm. Volumenya ...",
        ["770 cm^3", "1.540 cm^3", "2.200 cm^3", "4.400 cm^3"],
        "1.540 cm^3",
        "Volume = pi r^2 t = 22/7 x 7 x 7 x 10 = 1.540.",
      ),
      q(
        9,
        "w3",
        "Soal Cerita",
        "sedang",
        "Data 6, 8, 8, 10, 12 memiliki median ...",
        ["8", "9", "10", "12"],
        "8",
        "Data tengah dari lima data adalah data ke-3, yaitu 8.",
      ),
      q(
        9,
        "w4",
        "Soal Cerita",
        "menantang",
        "Dua segitiga sebangun memiliki perbandingan sisi 3 : 4. Jika luas kecil 27 cm^2, luas besar ...",
        ["36 cm^2", "48 cm^2", "64 cm^2", "81 cm^2"],
        "48 cm^2",
        "Perbandingan luas 9 : 16, maka luas besar = 27 x 16/9 = 48.",
      ),
      q(
        9,
        "l1",
        "Penalaran Logis",
        "sedang",
        "Pola 2, 5, 10, 17, 26, ... adalah ...",
        ["35", "37", "39", "41"],
        "37",
        "Selisihnya 3, 5, 7, 9, berikutnya 11, jadi 37.",
      ),
      q(
        9,
        "l2",
        "Penalaran Logis",
        "menantang",
        "Jika f(x)=x^2-2x, maka f(5)-f(3)= ...",
        ["8", "10", "12", "14"],
        "12",
        "f(5)=15 dan f(3)=3, selisihnya 12.",
      ),
      q(
        9,
        "l3",
        "Penalaran Logis",
        "sedang",
        "Jika peluang hujan 0,35, peluang tidak hujan adalah ...",
        ["0,35", "0,55", "0,65", "1,35"],
        "0,65",
        "Peluang komplemen = 1 - 0,35 = 0,65.",
      ),
      q(
        9,
        "l4",
        "Penalaran Logis",
        "menantang",
        "Jika 2 mesin membuat 18 barang per jam, maka 5 mesin membuat ... barang per jam.",
        ["36", "45", "54", "60"],
        "45",
        "1 mesin membuat 9 barang per jam, jadi 5 mesin membuat 45.",
      ),
    ];
  }

  if (g === 10) {
    return [
      q(
        10,
        "n1",
        "Pemahaman Bilangan",
        "sedang",
        "Daerah asal fungsi f(x)=\\frac{1}{x-3} mengecualikan x = ...",
        ["-3", "0", "3", "1"],
        "3",
        "Penyebut tidak boleh nol, jadi x - 3 tidak boleh 0.",
      ),
      q(
        10,
        "n2",
        "Pemahaman Bilangan",
        "sedang",
        "Bentuk interval dari x > 2 adalah ...",
        ["(-∞, 2)", "(2, ∞)", "[2, ∞)", "(-∞, 2]"],
        "(2, ∞)",
        "x lebih besar dari 2, tidak termasuk 2.",
      ),
      q(
        10,
        "n3",
        "Pemahaman Bilangan",
        "menantang",
        "Jika |x| = 7, maka x adalah ...",
        ["7 saja", "-7 saja", "-7 atau 7", "0 atau 7"],
        "-7 atau 7",
        "Nilai mutlak menunjukkan jarak dari nol, sehingga bisa -7 atau 7.",
      ),
      q(
        10,
        "n4",
        "Pemahaman Bilangan",
        "sedang",
        "Nilai log_10 1000 adalah ...",
        ["2", "3", "10", "100"],
        "3",
        "10^3 = 1000.",
      ),
      q(
        10,
        "a1",
        "Kelancaran Berhitung",
        "sedang",
        "Akar-akar x^2 - 7x + 12 = 0 adalah ...",
        ["1 dan 12", "3 dan 4", "-3 dan -4", "2 dan 6"],
        "3 dan 4",
        "Faktornya (x - 3)(x - 4).",
      ),
      q(
        10,
        "a2",
        "Kelancaran Berhitung",
        "menantang",
        "Jika f(x)=3x-2, maka f(4)= ...",
        ["8", "10", "12", "14"],
        "10",
        "f(4)=3(4)-2=10.",
      ),
      q(
        10,
        "a3",
        "Kelancaran Berhitung",
        "sedang",
        "Solusi 5x - 15 = 0 adalah ...",
        ["-3", "0", "3", "5"],
        "3",
        "5x = 15 sehingga x = 3.",
      ),
      q(
        10,
        "a4",
        "Kelancaran Berhitung",
        "menantang",
        "Jika 2x^2 = 50, nilai x positif adalah ...",
        ["3", "4", "5", "6"],
        "5",
        "x^2 = 25, maka x positif = 5.",
      ),
      q(
        10,
        "f1",
        "Pecahan",
        "sedang",
        "\\frac{x-1}{3}=5, maka x = ...",
        ["14", "15", "16", "17"],
        "16",
        "x - 1 = 15, jadi x = 16.",
      ),
      q(
        10,
        "f2",
        "Pecahan",
        "menantang",
        "\\frac{2x+1}{5}=3, maka x = ...",
        ["5", "6", "7", "8"],
        "7",
        "2x + 1 = 15, maka 2x = 14 dan x = 7.",
      ),
      q(
        10,
        "f3",
        "Pecahan",
        "sedang",
        "Rasio sin pada segitiga siku-siku adalah ...",
        ["depan/miring", "samping/miring", "depan/samping", "miring/depan"],
        "depan/miring",
        "sin adalah perbandingan sisi depan terhadap sisi miring.",
      ),
      q(
        10,
        "f4",
        "Pecahan",
        "menantang",
        "Jika tan A = \\frac{3}{4}, maka perbandingan sisi depan : samping adalah ...",
        ["3 : 4", "4 : 3", "3 : 5", "5 : 4"],
        "3 : 4",
        "tan = depan/samping.",
      ),
      q(
        10,
        "w1",
        "Soal Cerita",
        "sedang",
        "Sebuah fungsi biaya C(x)=5000x+20000. Biaya untuk 6 barang adalah ...",
        ["Rp30.000", "Rp40.000", "Rp50.000", "Rp60.000"],
        "Rp50.000",
        "C(6)=5000(6)+20000=50.000.",
      ),
      q(
        10,
        "w2",
        "Soal Cerita",
        "menantang",
        "Sebuah bola dilempar dengan h(t)=-t^2+6t. Tinggi maksimum terjadi saat t = ...",
        ["2", "3", "4", "6"],
        "3",
        "Puncak parabola t = -b/(2a) = -6/(2(-1)) = 3.",
      ),
      q(
        10,
        "w3",
        "Soal Cerita",
        "sedang",
        "Jika rata-rata 5 nilai adalah 80, jumlah semua nilai adalah ...",
        ["85", "160", "400", "500"],
        "400",
        "Jumlah = rata-rata x banyak data = 80 x 5 = 400.",
      ),
      q(
        10,
        "w4",
        "Soal Cerita",
        "menantang",
        "Peluang memilih kartu merah dari 10 kartu merah dan 15 kartu biru adalah ...",
        ["\\frac{2}{5}", "\\frac{1}{2}", "\\frac{3}{5}", "\\frac{2}{3}"],
        "\\frac{2}{5}",
        "Peluang = 10/(10+15) = 10/25 = 2/5.",
      ),
      q(
        10,
        "l1",
        "Penalaran Logis",
        "sedang",
        "Jika f(x)=2x+1 dan g(x)=x^2, maka g(f(2)) = ...",
        ["9", "16", "25", "36"],
        "25",
        "f(2)=5, lalu g(5)=25.",
      ),
      q(
        10,
        "l2",
        "Penalaran Logis",
        "menantang",
        "Barisan 3, 7, 11, 15 memiliki suku ke-10 ...",
        ["35", "39", "43", "47"],
        "39",
        "Barisan aritmetika beda 4: U10 = 3 + 9(4) = 39.",
      ),
      q(
        10,
        "l3",
        "Penalaran Logis",
        "sedang",
        "Garis y=2x+3 dan y=2x-5 adalah ...",
        ["berpotongan", "sejajar", "tegak lurus", "berimpit"],
        "sejajar",
        "Gradien sama, konstanta berbeda, maka sejajar.",
      ),
      q(
        10,
        "l4",
        "Penalaran Logis",
        "menantang",
        "Jika diskriminan persamaan kuadrat negatif, jumlah akar realnya ...",
        ["0", "1", "2", "tak hingga"],
        "0",
        "Diskriminan negatif berarti tidak memiliki akar real.",
      ),
    ];
  }

  if (g === 11) {
    return makeGradeElevenBank();
  }
  return makeGradeTwelveBank();
}

function makeGradeElevenBank(): DiagnosticQuestion[] {
  return [
    q(
      11,
      "n1",
      "Pemahaman Bilangan",
      "sedang",
      "Nilai sin 30 derajat adalah ...",
      ["\\frac{1}{2}", "\\frac{\\sqrt{2}}{2}", "\\frac{\\sqrt{3}}{2}", "1"],
      "\\frac{1}{2}",
      "Nilai khusus sin 30 derajat adalah 1/2.",
    ),
    q(
      11,
      "n2",
      "Pemahaman Bilangan",
      "sedang",
      "Jika matriks A berordo 2 x 3, banyak elemennya ...",
      ["2", "3", "5", "6"],
      "6",
      "Matriks 2 x 3 memiliki 2 baris dan 3 kolom, total 6 elemen.",
    ),
    q(
      11,
      "n3",
      "Pemahaman Bilangan",
      "menantang",
      "Determinan matriks [[2,3],[1,4]] adalah ...",
      ["5", "6", "8", "11"],
      "5",
      "Determinan = 2(4) - 3(1) = 5.",
    ),
    q(
      11,
      "n4",
      "Pemahaman Bilangan",
      "sedang",
      "Jika vektor a=(3,4), panjang vektor a adalah ...",
      ["5", "6", "7", "12"],
      "5",
      "Panjang = sqrt(3^2 + 4^2) = 5.",
    ),
    q(
      11,
      "a1",
      "Kelancaran Berhitung",
      "sedang",
      "Turunan dari f(x)=x^3 adalah ...",
      ["x^2", "2x", "3x^2", "3x"],
      "3x^2",
      "Gunakan aturan pangkat: turunan x^3 adalah 3x^2.",
    ),
    q(
      11,
      "a2",
      "Kelancaran Berhitung",
      "menantang",
      "Turunan dari 4x^2 - 5x + 7 adalah ...",
      ["8x - 5", "8x + 5", "4x - 5", "2x - 5"],
      "8x - 5",
      "Turunan 4x^2 adalah 8x, turunan -5x adalah -5.",
    ),
    q(
      11,
      "a3",
      "Kelancaran Berhitung",
      "sedang",
      "Jika f(x)=x^2+2x, maka f'(3)= ...",
      ["6", "7", "8", "9"],
      "8",
      "f'(x)=2x+2, jadi f'(3)=8.",
    ),
    q(
      11,
      "a4",
      "Kelancaran Berhitung",
      "menantang",
      "Hasil komposisi f(g(2)) untuk f(x)=3x+1 dan g(x)=x^2 adalah ...",
      ["7", "10", "13", "15"],
      "13",
      "g(2)=4, f(4)=13.",
    ),
    q(
      11,
      "f1",
      "Pecahan",
      "sedang",
      "Peluang mengambil bola merah dari 3 merah dan 5 biru adalah ...",
      ["\\frac{3}{8}", "\\frac{5}{8}", "\\frac{3}{5}", "\\frac{8}{3}"],
      "\\frac{3}{8}",
      "Total bola 8, merah 3, peluang 3/8.",
    ),
    q(
      11,
      "f2",
      "Pecahan",
      "menantang",
      "Jika P(A)=0,6 dan P(B)=0,4 serta saling lepas, maka P(A atau B)= ...",
      ["0,2", "0,6", "0,8", "1,0"],
      "1,0",
      "Untuk kejadian saling lepas, peluang dijumlahkan: 0,6 + 0,4 = 1,0.",
    ),
    q(
      11,
      "f3",
      "Pecahan",
      "sedang",
      "Rata-rata dari 6, 8, 10, 12 adalah ...",
      ["8", "9", "10", "11"],
      "9",
      "Jumlah 36 dibagi 4 = 9.",
    ),
    q(
      11,
      "f4",
      "Pecahan",
      "menantang",
      "Jika data memiliki mean 12 dan jumlah data 6, total data adalah ...",
      ["18", "36", "60", "72"],
      "72",
      "Total = mean x banyak data = 12 x 6 = 72.",
    ),
    q(
      11,
      "w1",
      "Soal Cerita",
      "sedang",
      "Sebuah tangga 10 m bersandar pada tembok. Jarak kaki tangga ke tembok 6 m. Tinggi tembok yang dicapai ...",
      ["6 m", "7 m", "8 m", "9 m"],
      "8 m",
      "Gunakan Pythagoras: tinggi = sqrt(10^2 - 6^2) = 8.",
    ),
    q(
      11,
      "w2",
      "Soal Cerita",
      "menantang",
      "Sebuah investasi Rp2.000.000 berbunga 10% setahun. Setelah 1 tahun menjadi ...",
      ["Rp2.100.000", "Rp2.200.000", "Rp2.300.000", "Rp2.400.000"],
      "Rp2.200.000",
      "Bunga = 10% x 2.000.000 = 200.000.",
    ),
    q(
      11,
      "w3",
      "Soal Cerita",
      "sedang",
      "Jika cos A = 12/13, sisi samping 12 dan miring 13, sisi depan adalah ...",
      ["1", "5", "7", "25"],
      "5",
      "Dengan Pythagoras, depan = sqrt(13^2 - 12^2) = 5.",
    ),
    q(
      11,
      "w4",
      "Soal Cerita",
      "menantang",
      "Biaya total C(x)=x^2+10x+100. Biaya marginal saat x=5 adalah ...",
      ["10", "15", "20", "25"],
      "20",
      "Biaya marginal adalah turunan C'(x)=2x+10, maka C'(5)=20.",
    ),
    q(
      11,
      "l1",
      "Penalaran Logis",
      "sedang",
      "Jika suku pertama 5 dan beda 3, suku ke-8 barisan aritmetika adalah ...",
      ["23", "26", "29", "32"],
      "26",
      "U8 = 5 + 7(3) = 26.",
    ),
    q(
      11,
      "l2",
      "Penalaran Logis",
      "menantang",
      "Jumlah 5 suku pertama deret 2 + 4 + 8 + ... adalah ...",
      ["30", "31", "62", "64"],
      "62",
      "Deret geometri: 2+4+8+16+32 = 62.",
    ),
    q(
      11,
      "l3",
      "Penalaran Logis",
      "sedang",
      "Jika dua vektor tegak lurus, hasil dot product-nya ...",
      ["-1", "0", "1", "tak hingga"],
      "0",
      "Vektor tegak lurus memiliki dot product 0.",
    ),
    q(
      11,
      "l4",
      "Penalaran Logis",
      "menantang",
      "Jika f'(x)>0 pada suatu interval, grafik f pada interval itu ...",
      ["naik", "turun", "konstan", "terputus"],
      "naik",
      "Turunan positif menunjukkan fungsi naik.",
    ),
  ];
}

function makeGradeTwelveBank(): DiagnosticQuestion[] {
  return [
    q(
      12,
      "n1",
      "Pemahaman Bilangan",
      "sedang",
      "Limit lim x->2 dari (x^2 - 4)/(x - 2) adalah ...",
      ["0", "2", "4", "tidak ada"],
      "4",
      "Faktorkan x^2-4=(x-2)(x+2), limit menjadi x+2 saat x=2, yaitu 4.",
    ),
    q(
      12,
      "n2",
      "Pemahaman Bilangan",
      "sedang",
      "Integral dari 2x adalah ...",
      ["x", "x^2 + C", "2x^2 + C", "x^2"],
      "x^2 + C",
      "Integral 2x adalah x^2 + C.",
    ),
    q(
      12,
      "n3",
      "Pemahaman Bilangan",
      "menantang",
      "Jika log 100 = 2, maka log 10.000 = ...",
      ["2", "3", "4", "5"],
      "4",
      "10.000 = 10^4, jadi log 10.000 = 4.",
    ),
    q(
      12,
      "n4",
      "Pemahaman Bilangan",
      "sedang",
      "Nilai e^0 adalah ...",
      ["0", "1", "e", "tidak terdefinisi"],
      "1",
      "Setiap bilangan tak nol berpangkat 0 bernilai 1.",
    ),
    q(
      12,
      "a1",
      "Kelancaran Berhitung",
      "sedang",
      "Turunan dari sin x adalah ...",
      ["cos x", "-cos x", "sin x", "-sin x"],
      "cos x",
      "Turunan sin x adalah cos x.",
    ),
    q(
      12,
      "a2",
      "Kelancaran Berhitung",
      "menantang",
      "Integral dari 3x^2 adalah ...",
      ["x^3 + C", "3x^3 + C", "6x + C", "x^2 + C"],
      "x^3 + C",
      "Integral 3x^2 adalah x^3 + C.",
    ),
    q(
      12,
      "a3",
      "Kelancaran Berhitung",
      "sedang",
      "Jika f(x)=x^2, maka f'(4)= ...",
      ["4", "6", "8", "16"],
      "8",
      "f'(x)=2x, maka f'(4)=8.",
    ),
    q(
      12,
      "a4",
      "Kelancaran Berhitung",
      "menantang",
      "Nilai maksimum fungsi -x^2+4x terjadi saat x = ...",
      ["1", "2", "3", "4"],
      "2",
      "Puncak parabola x = -b/(2a) = -4/(2(-1)) = 2.",
    ),
    q(
      12,
      "f1",
      "Pecahan",
      "sedang",
      "Peluang dua sisi koin sama-sama gambar dalam dua lemparan adalah ...",
      ["\\frac{1}{4}", "\\frac{1}{2}", "\\frac{3}{4}", "1"],
      "\\frac{1}{4}",
      "Kemungkinan GG hanya 1 dari 4 hasil.",
    ),
    q(
      12,
      "f2",
      "Pecahan",
      "menantang",
      "Peluang mengambil 1 kartu As dari 52 kartu adalah ...",
      ["\\frac{1}{52}", "\\frac{1}{13}", "\\frac{4}{13}", "\\frac{13}{52}"],
      "\\frac{1}{13}",
      "Ada 4 As dari 52 kartu, jadi 4/52 = 1/13.",
    ),
    q(
      12,
      "f3",
      "Pecahan",
      "sedang",
      "Jika P(A)=0,7, peluang komplemen A adalah ...",
      ["0,2", "0,3", "0,7", "1,7"],
      "0,3",
      "P(A') = 1 - 0,7 = 0,3.",
    ),
    q(
      12,
      "f4",
      "Pecahan",
      "menantang",
      "Nilai rata-rata 80 dari 5 data berarti jumlah data ...",
      ["85", "160", "400", "500"],
      "400",
      "Jumlah = mean x n = 80 x 5 = 400.",
    ),
    q(
      12,
      "w1",
      "Soal Cerita",
      "sedang",
      "Kecepatan berubah s(t)=t^2+3t. Kecepatan sesaat saat t=4 adalah ...",
      ["7", "8", "11", "14"],
      "11",
      "Kecepatan adalah turunan s'(t)=2t+3, jadi s'(4)=11.",
    ),
    q(
      12,
      "w2",
      "Soal Cerita",
      "menantang",
      "Luas daerah di bawah y=2x dari x=0 sampai x=3 adalah ...",
      ["3", "6", "9", "12"],
      "9",
      "Integral 2x dari 0 ke 3 adalah x^2|0^3 = 9.",
    ),
    q(
      12,
      "w3",
      "Soal Cerita",
      "sedang",
      "Modal Rp1.000.000 tumbuh 5% menjadi ...",
      ["Rp1.005.000", "Rp1.050.000", "Rp1.500.000", "Rp5.000.000"],
      "Rp1.050.000",
      "5% dari 1.000.000 = 50.000, total 1.050.000.",
    ),
    q(
      12,
      "w4",
      "Soal Cerita",
      "menantang",
      "Jika biaya marginal C'(x)=6x dan biaya tambahan dari x=0 ke x=5 adalah ...",
      ["30", "75", "150", "180"],
      "75",
      "Integral 6x dari 0 ke 5 adalah 3x^2|0^5 = 75.",
    ),
    q(
      12,
      "l1",
      "Penalaran Logis",
      "sedang",
      "Jika f'(x)=0 di titik dalam domain, titik tersebut mungkin ...",
      ["titik kritis", "asimtot", "akar mutlak", "domain kosong"],
      "titik kritis",
      "Titik dengan turunan nol adalah kandidat titik kritis.",
    ),
    q(
      12,
      "l2",
      "Penalaran Logis",
      "menantang",
      "Jika f''(x)>0, grafik cekung ke ...",
      ["atas", "bawah", "kiri", "kanan"],
      "atas",
      "Turunan kedua positif menunjukkan grafik cekung ke atas.",
    ),
    q(
      12,
      "l3",
      "Penalaran Logis",
      "sedang",
      "Barisan geometri 3, 6, 12, ... memiliki rasio ...",
      ["2", "3", "6", "12"],
      "2",
      "Rasio = 6 : 3 = 2.",
    ),
    q(
      12,
      "l4",
      "Penalaran Logis",
      "menantang",
      "Jika peluang A dan B independen, P(A dan B) = ...",
      ["P(A)+P(B)", "P(A)-P(B)", "P(A) x P(B)", "P(A)/P(B)"],
      "P(A) x P(B)",
      "Untuk kejadian independen, peluang irisan adalah hasil kali peluang.",
    ),
  ];
}

function makeUpperGradeBank(gradeLevel: number): DiagnosticQuestion[] {
  const base = Math.max(7, gradeLevel);
  return [
    q(
      base,
      "n1",
      "Pemahaman Bilangan",
      "sedang",
      "Bentuk sederhana dari 18 : 24 adalah ...",
      ["2 : 3", "3 : 4", "4 : 3", "6 : 8"],
      "3 : 4",
      "18 dan 24 dibagi FPB 6 menjadi 3 : 4.",
    ),
    q(
      base,
      "a1",
      "Kelancaran Berhitung",
      "sedang",
      "3^2 + 4^2 = ...",
      ["12", "17", "25", "49"],
      "25",
      "3^2 = 9 dan 4^2 = 16, total 25.",
    ),
    q(
      base,
      "a2",
      "Kelancaran Berhitung",
      "menantang",
      "Jika x = 5, nilai 2x + 7 adalah ...",
      ["12", "15", "17", "19"],
      "17",
      "2(5) + 7 = 17.",
    ),
    q(
      base,
      "f1",
      "Pecahan",
      "sedang",
      "\\frac{3}{4} dari 80 adalah ...",
      ["20", "40", "60", "75"],
      "60",
      "80 : 4 x 3 = 60.",
    ),
    q(
      base,
      "f2",
      "Pecahan",
      "menantang",
      "0,125 sama dengan ...",
      ["\\frac{1}{4}", "\\frac{1}{8}", "\\frac{2}{5}", "\\frac{3}{8}"],
      "\\frac{1}{8}",
      "0,125 = 125/1000 = 1/8.",
    ),
    q(
      base,
      "w1",
      "Soal Cerita",
      "sedang",
      "Sebuah barang Rp200.000 diberi diskon 15%. Harga setelah diskon adalah ...",
      ["Rp150.000", "Rp160.000", "Rp170.000", "Rp185.000"],
      "Rp170.000",
      "Diskon 15% dari 200.000 = 30.000, harga akhir 170.000.",
    ),
    q(
      base,
      "l1",
      "Penalaran Logis",
      "menantang",
      "Pola: 2, 6, 18, 54, ...",
      ["108", "120", "144", "162"],
      "162",
      "Pola dikali 3.",
    ),
    q(
      base,
      "w2",
      "Soal Cerita",
      "menantang",
      "Perbandingan A:B = 2:3. Jika total 50, nilai B adalah ...",
      ["20", "25", "30", "35"],
      "30",
      "Total bagian 5, B = 3/5 x 50 = 30.",
    ),
  ];
}

function makeSupplementalBank(gradeLevel: number): DiagnosticQuestion[] {
  if (gradeLevel === 1) {
    return [
      q(
        1,
        "s1",
        "Pemahaman Bilangan",
        "mudah",
        "Bilangan yang berada di antara 24 dan 26 adalah ...",
        ["23", "24", "25", "27"],
        "25",
        "Urutan bilangannya adalah 24, 25, 26.",
      ),
      q(
        1,
        "s2",
        "Kelancaran Berhitung",
        "mudah",
        "8 + 6 = ...",
        ["12", "13", "14", "15"],
        "14",
        "8 + 6 = 14.",
      ),
      q(
        1,
        "s3",
        "Kelancaran Berhitung",
        "sedang",
        "20 - 9 = ...",
        ["9", "10", "11", "12"],
        "11",
        "20 dikurangi 9 tersisa 11.",
      ),
      q(
        1,
        "s4",
        "Soal Cerita",
        "sedang",
        "Doni punya 12 kelereng. Ia memberi 5 kelereng kepada teman. Sisa kelereng Doni ...",
        ["5", "6", "7", "8"],
        "7",
        "12 - 5 = 7.",
      ),
      q(
        1,
        "s5",
        "Penalaran Logis",
        "sedang",
        "Pola: 1, 3, 5, 7, ...",
        ["8", "9", "10", "11"],
        "9",
        "Pola bertambah 2.",
      ),
      q(
        1,
        "s6",
        "Pemahaman Bilangan",
        "mudah",
        "Bilangan 32 memiliki ... puluhan.",
        ["2", "3", "30", "32"],
        "3",
        "Pada 32, angka 3 berada di tempat puluhan.",
      ),
      q(
        1,
        "s7",
        "Kelancaran Berhitung",
        "sedang",
        "Jika 6 + ... = 15, maka titik-titik berisi ...",
        ["7", "8", "9", "10"],
        "9",
        "15 - 6 = 9.",
      ),
      q(
        1,
        "s8",
        "Soal Cerita",
        "sedang",
        "Ada 4 piring. Setiap piring berisi 2 kue. Jumlah kue semuanya ...",
        ["6", "8", "10", "12"],
        "8",
        "4 kelompok berisi 2 berarti 4 x 2 = 8.",
      ),
      q(
        1,
        "s9",
        "Pemahaman Bilangan",
        "mudah",
        "Mana bilangan yang paling kecil?",
        ["27", "17", "21", "31"],
        "17",
        "17 lebih kecil daripada 21, 27, dan 31.",
      ),
      q(
        1,
        "s10",
        "Pecahan",
        "sedang",
        "Setengah dari 8 kue adalah ... kue",
        ["2", "3", "4", "6"],
        "4",
        "Setengah berarti dibagi 2, jadi 8 : 2 = 4.",
      ),
      q(
        1,
        "s11",
        "Kelancaran Berhitung",
        "sedang",
        "13 + 4 - 5 = ...",
        ["10", "11", "12", "13"],
        "12",
        "13 + 4 = 17, lalu 17 - 5 = 12.",
      ),
      q(
        1,
        "s12",
        "Soal Cerita",
        "sedang",
        "Sari membaca 8 halaman pagi hari dan 7 halaman sore hari. Total halaman yang dibaca ...",
        ["13", "14", "15", "16"],
        "15",
        "8 + 7 = 15.",
      ),
    ];
  }

  const g = Math.max(2, gradeLevel);
  const placeNumber = g <= 3 ? 486 : g <= 5 ? 48_635 : 348_720;
  const addA = g * 37 + 124;
  const addB = g * 28 + 96;
  const addResult = addA + addB;
  const subA = g * 90 + 315;
  const subB = g * 25 + 88;
  const subResult = subA - subB;
  const multiplyA = g + 6;
  const multiplyB = g + 8;
  const multiplyResult = multiplyA * multiplyB;
  const storyEach = g + 4;
  const storyGroup = g + 3;
  const storyTotal = storyEach * storyGroup;
  const fractionTotal = (g + 2) * (g + 3);
  const fractionAnswer = g + 3;
  const patternStart = g;
  const patternStep = g + 1;
  const patternNext = patternStart + patternStep * 4;

  return [
    q(
      g,
      "s1",
      "Pemahaman Bilangan",
      "sedang",
      `Nilai angka 8 pada bilangan ${placeNumber.toLocaleString("id-ID")} adalah ...`,
      ["8", "80", "800", "8.000"],
      placeNumber >= 10_000 ? "8.000" : "80",
      placeNumber >= 10_000
        ? "Angka 8 berada pada tempat ribuan."
        : "Angka 8 berada pada tempat puluhan.",
    ),
    q(
      g,
      "s2",
      "Kelancaran Berhitung",
      "sedang",
      `${addA.toLocaleString("id-ID")} + ${addB.toLocaleString("id-ID")} = ...`,
      [
        String(addResult - 20),
        String(addResult - 10),
        String(addResult),
        String(addResult + 10),
      ].map((v) => Number(v).toLocaleString("id-ID")),
      addResult.toLocaleString("id-ID"),
      `Hasil penjumlahan adalah ${addResult.toLocaleString("id-ID")}.`,
    ),
    q(
      g,
      "s3",
      "Kelancaran Berhitung",
      "sedang",
      `${subA.toLocaleString("id-ID")} - ${subB.toLocaleString("id-ID")} = ...`,
      [subResult - 10, subResult, subResult + 10, subResult + 20].map((v) =>
        v.toLocaleString("id-ID"),
      ),
      subResult.toLocaleString("id-ID"),
      `Hasil pengurangan adalah ${subResult.toLocaleString("id-ID")}.`,
    ),
    q(
      g,
      "s4",
      "Kelancaran Berhitung",
      "sedang",
      `${multiplyA} x ${multiplyB} = ...`,
      [
        multiplyResult - multiplyA,
        multiplyResult - 1,
        multiplyResult,
        multiplyResult + multiplyB,
      ].map(String),
      String(multiplyResult),
      `${multiplyA} x ${multiplyB} = ${multiplyResult}.`,
    ),
    q(
      g,
      "s5",
      "Pecahan",
      "sedang",
      `\\frac{1}{${g + 2}} dari ${storyTotal} adalah ...`,
      [
        String(storyGroup - 1),
        String(storyGroup),
        String(storyEach),
        String(storyTotal),
      ].filter((v, i, a) => a.indexOf(v) === i),
      String(storyGroup),
      `${storyTotal} : ${g + 2} = ${storyGroup}.`,
    ),
    q(
      g,
      "s6",
      "Soal Cerita",
      "sedang",
      `Ada ${storyGroup} kotak. Setiap kotak berisi ${storyEach} pensil. Jumlah pensil seluruhnya ...`,
      [
        storyTotal - storyEach,
        storyTotal - 1,
        storyTotal,
        storyTotal + storyEach,
      ].map(String),
      String(storyTotal),
      `${storyGroup} x ${storyEach} = ${storyTotal}.`,
    ),
    q(
      g,
      "s7",
      "Penalaran Logis",
      "sedang",
      `Pola: ${patternStart}, ${patternStart + patternStep}, ${patternStart + patternStep * 2}, ${patternStart + patternStep * 3}, ...`,
      [patternNext - 2, patternNext - 1, patternNext, patternNext + 1].map(
        String,
      ),
      String(patternNext),
      `Pola bertambah ${patternStep}, jadi suku berikutnya adalah ${patternNext}.`,
    ),
    q(
      g,
      "s8",
      "Soal Cerita",
      "menantang",
      `Raka membeli ${g + 2} buku seharga Rp${(g * 1000 + 6000).toLocaleString("id-ID")} per buku. Total uang yang harus dibayar ...`,
      [
        `Rp${((g + 1) * (g * 1000 + 6000)).toLocaleString("id-ID")}`,
        `Rp${((g + 2) * (g * 1000 + 6000)).toLocaleString("id-ID")}`,
        `Rp${((g + 3) * (g * 1000 + 6000)).toLocaleString("id-ID")}`,
        `Rp${((g + 4) * (g * 1000 + 6000)).toLocaleString("id-ID")}`,
      ],
      `Rp${((g + 2) * (g * 1000 + 6000)).toLocaleString("id-ID")}`,
      "Total harga = banyak barang x harga satuan.",
    ),
    q(
      g,
      "s9",
      "Pemahaman Bilangan",
      "sedang",
      `Bilangan ${placeNumber.toLocaleString("id-ID")} dibulatkan ke ratusan terdekat menjadi ...`,
      [
        (Math.round(placeNumber / 100) * 100 - 100).toLocaleString("id-ID"),
        (Math.round(placeNumber / 100) * 100).toLocaleString("id-ID"),
        (Math.round(placeNumber / 100) * 100 + 100).toLocaleString("id-ID"),
        (Math.round(placeNumber / 100) * 100 + 1000).toLocaleString("id-ID"),
      ],
      (Math.round(placeNumber / 100) * 100).toLocaleString("id-ID"),
      "Lihat angka puluhan untuk membulatkan ke ratusan terdekat.",
    ),
    q(
      g,
      "s10",
      "Pecahan",
      "menantang",
      `Pecahan senilai dengan \\frac{${g}}{${g + 2}} adalah ...`,
      [
        `\\frac{${g + 1}}{${g + 3}}`,
        `\\frac{${g * 2}}{${(g + 2) * 2}}`,
        `\\frac{${g * 2 + 1}}{${(g + 2) * 2}}`,
        `\\frac{${g}}{${g + 3}}`,
      ],
      `\\frac{${g * 2}}{${(g + 2) * 2}}`,
      "Pecahan senilai diperoleh dengan mengalikan pembilang dan penyebut dengan bilangan yang sama.",
    ),
    q(
      g,
      "s11",
      "Penalaran Logis",
      "menantang",
      `Jika 4 paket berisi ${4 * (g + 5)} stiker, maka 7 paket berisi ... stiker.`,
      [
        String(6 * (g + 5)),
        String(7 * (g + 5)),
        String(8 * (g + 5)),
        String(9 * (g + 5)),
      ],
      String(7 * (g + 5)),
      `Isi 1 paket = ${4 * (g + 5)} : 4 = ${g + 5}, jadi 7 paket = ${7 * (g + 5)}.`,
    ),
    q(
      g,
      "s12",
      "Soal Cerita",
      "menantang",
      `Sebuah persegi memiliki sisi ${g + 5} cm. Luasnya adalah ...`,
      [
        `${(g + 5) * 2} cm^2`,
        `${(g + 5) * 3} cm^2`,
        `${(g + 5) ** 2} cm^2`,
        `${(g + 5) ** 2 + 10} cm^2`,
      ],
      `${(g + 5) ** 2} cm^2`,
      `Luas persegi = sisi x sisi = ${g + 5} x ${g + 5} = ${(g + 5) ** 2} cm^2.`,
    ),
  ];
}

export function getGradeLabel(gradeLevel: number) {
  return gradeNames[gradeLevel - 1] ?? `Kelas ${gradeLevel}`;
}

function rekeyQuestions(
  questions: DiagnosticQuestion[],
  targetGradeLevel: number,
  prefix: string,
) {
  return questions.map((question, index) => ({
    ...question,
    id: `g${targetGradeLevel}-${prefix}${index + 1}`,
    gradeLevel: targetGradeLevel,
    skillLevel: question.skillLevel,
    recommendationKey: question.recommendationKey.replace(
      /^G\d+_/,
      `G${targetGradeLevel}_`,
    ),
  }));
}

function makeElementaryQuestionSet(sourceGradeLevel: number) {
  const baseQuestions =
    banks[sourceGradeLevel] ?? makeUpperGradeBank(sourceGradeLevel);
  return [...baseQuestions, ...makeSupplementalBank(sourceGradeLevel)].slice(
    0,
    20,
  );
}

function makeSmpQuestionSet() {
  const kelas6Sd = makeElementaryQuestionSet(6).slice(0, 10);
  const kelas1Smp = makeSecondaryGradeBank(7).slice(0, 10);
  return [...kelas6Sd, ...kelas1Smp].slice(0, 20);
}

function makeSmaQuestionSet() {
  const smpFoundation = makeSmpQuestionSet().slice(0, 10);
  const kelas1Sma = makeSecondaryGradeBank(10).slice(0, 10);
  return [...smpFoundation, ...kelas1Sma].slice(0, 20);
}

export function getDiagnosticQuestions(gradeLevel: number) {
  // Grade 1 sudah menggunakan Diagnostic V2.
  // Jangan melewati legacy rekey/supplemental flow agar metadata tetap utuh.
  if (gradeLevel === 1) {
    return grade1DiagnosticV2;
  }

  // Grade 2-12 masih menggunakan legacy question bank sementara
  // sampai masing-masing grade dimigrasikan ke BSMATH_Gx_V1.
  if (gradeLevel === 2) {
    return rekeyQuestions(makeElementaryQuestionSet(1), gradeLevel, "sd-awal-");
  }
  if (gradeLevel <= 4) {
    return rekeyQuestions(
      makeElementaryQuestionSet(3),
      gradeLevel,
      "sd-tengah-",
    );
  }
  if (gradeLevel <= 6) {
    return rekeyQuestions(makeElementaryQuestionSet(5), gradeLevel, "sd-atas-");
  }
  if (gradeLevel <= 9) {
    return rekeyQuestions(makeSmpQuestionSet(), gradeLevel, "smp-");
  }
  return rekeyQuestions(makeSmaQuestionSet(), gradeLevel, "sma-");
}

export function getDiagnosticQuestionMap(gradeLevel: number) {
  return new Map(
    getDiagnosticQuestions(gradeLevel).map((question) => [
      question.id,
      question,
    ]),
  );
}

export function getScoreProfile(score: number): DiagnosticProfile {
  if (score >= 85) {
    return {
      level: "Sangat Siap",
      tone: "Anak menunjukkan kesiapan matematika yang kuat.",
      summary:
        "Kemampuan dasar dan penalaran anak berada di atas ekspektasi untuk level kelasnya.",
      recommendation: [
        "Berikan soal eksplorasi dan tantangan HOTS agar anak tetap berkembang.",
        "Pertahankan latihan rutin singkat 2-3 kali per minggu.",
        "Mulai kenalkan strategi pemecahan soal cerita yang lebih kompleks.",
      ],
    };
  }
  if (score >= 70) {
    return {
      level: "Sesuai Jalur",
      tone: "Anak berada di jalur yang baik, tetapi masih ada area yang bisa dikuatkan.",
      summary:
        "Konsep utama cukup dipahami, namun konsistensi dan ketelitian masih perlu dilatih.",
      recommendation: [
        "Latih variasi soal dari topik yang nilainya paling rendah.",
        "Gunakan review mingguan agar konsep tidak mudah lupa.",
        "Kombinasikan soal hitungan cepat dan soal cerita pendek.",
      ],
    };
  }
  if (score >= 50) {
    return {
      level: "Perlu Pendampingan",
      tone: "Anak membutuhkan penguatan terarah pada beberapa konsep penting.",
      summary:
        "Ada fondasi yang sudah terbentuk, tetapi beberapa topik inti belum stabil.",
      recommendation: [
        "Mulai dari konsep prasyarat sebelum mengejar materi baru.",
        "Gunakan visual, benda konkret, dan contoh bertahap.",
        "Jadwalkan pendampingan belajar agar kesulitan tidak menumpuk.",
      ],
    };
  }
  return {
    level: "Fondasi Perlu Dikuatkan",
    tone: "Anak perlu membangun ulang fondasi matematika secara bertahap.",
    summary:
      "Beberapa kemampuan dasar belum siap menopang materi kelas saat ini.",
    recommendation: [
      "Fokus pada bilangan, operasi dasar, dan pemahaman soal sederhana.",
      "Gunakan sesi belajar pendek tetapi konsisten.",
      "Hindari langsung memberi soal sulit sebelum fondasi lebih stabil.",
    ],
  };
}

export const diagnosticCategories: DiagnosticCategory[] = [
  "Pemahaman Bilangan",
  "Kelancaran Berhitung",
  "Pecahan",
  "Soal Cerita",
  "Penalaran Logis",
];
